# Generated by Django 4.2.4 on 2024-12-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "annotation_backend",
            "0002_remove_annotation_height_remove_annotation_width_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="height",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="annotation",
            name="width",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="annotation",
            name="x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="annotation",
            name="y",
            field=models.FloatField(default=0),
        ),
    ]
